safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:     /
url:         http://localhost:4000
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
markdown:    maruku
permalink:   date

exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, vendor]

sass:
    syntax: scss
    style:  compressed
